# Generated by Django 5.1.7 on 2025-03-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ADM', 'Admin'), ('ALN', 'Aluno')], max_length=3),
        ),
    ]
