# Generated by Django 5.1.7 on 2025-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_aluno',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
